[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ercot_scraping"
version = "0.1.0"
dependencies = [
    "pandas",
    "requests",
    "logging",
    "python-dotenv",
]
requires-python = "==3.11.9"

[project.scripts]
fetch_prices = "ercot_scraping.run:main"

[project.optional-dependencies]
test = [
    "pytest>=6.2.4",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
