[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ercot-project"
version = "0.1.0"
dependencies = [
    "pandas",
    "requests",
    "logging",
]
