# New mappings for different CSV types
COLUMN_MAPPINGS = {
    "settlement_point_prices": {
        "deliverydate": "deliveryDate",
        "delivery_date": "deliveryDate",
        "deliveryhour": "deliveryHour",
        "delivery_hour": "deliveryHour",
        "deliveryinterval": "deliveryInterval",
        "delivery_interval": "deliveryInterval",
        "settlementPoint": "settlementPointName",
        "settlementpointname": "settlementPointName",
        "settlement_point_name": "settlementPointName",
        "settlementpointtype": "settlementPointType",
        "settlement_point_type": "settlementPointType",
        "settlementpointprice": "settlementPointPrice",
        "settlement_point_price": "settlementPointPrice",
        "dstflag": "dstFlag",
        "dst_flag": "dstFlag",
        "DSTFlag": "dstFlag",
    },
    "bid_awards": {
        "delivery date": "deliveryDate",
        "delivery_date": "deliveryDate",
        "hour ending": "hourEnding",
        "hour_ending": "hourEnding",
        "settlement point": "settlementPointName",
        "settlement_point": "settlementPointName",
        "qse name": "qseName",
        "qse_name": "qseName",
        "energy only bid award in mw": "energyOnlyBidAwardInMW",
        "energy_only_bid_award_in_mw": "energyOnlyBidAwardInMW",
        "settlement point price": "settlementPointPrice",
        "settlement_point_price": "settlementPointPrice",
        "bid id": "bidId",
        "bid_id": "bidId",
    },
    "bids": {
        "delivery date": "deliveryDate",
        "delivery_date": "deliveryDate",
        "hour ending": "hourEnding",
        "hour_ending": "hourEnding",
        "settlement point": "settlementPointName",
        "settlement_point": "settlementPointName",
        "qse name": "qseName",
        "qse_name": "qseName",
        "energy only bid mw1": "energyOnlyBidMw1",
        "energy_only_bid_mw1": "energyOnlyBidMw1",
        "energy only bid price1": "energyOnlyBidPrice1",
        "energy_only_bid_price1": "energyOnlyBidPrice1",
        "energy only bid mw2": "energyOnlyBidMw2",
        "energy_only_bid_mw2": "energyOnlyBidMw2",
        "energy only bid price2": "energyOnlyBidPrice2",
        "energy_only_bid_price2": "energyOnlyBidPrice2",
        "energy only bid mw3": "energyOnlyBidMw3",
        "energy_only_bid_mw3": "energyOnlyBidMw3",
        "energy only bid price3": "energyOnlyBidPrice3",
        "energy_only_bid_price3": "energyOnlyBidPrice3",
        "energy only bid mw4": "energyOnlyBidMw4",
        "energy_only_bid_mw4": "energyOnlyBidMw4",
        "energy only bid price4": "energyOnlyBidPrice4",
        "energy_only_bid_price4": "energyOnlyBidPrice4",
        "energy only bid mw5": "energyOnlyBidMw5",
        "energy_only_bid_mw5": "energyOnlyBidMw5",
        "energy only bid price5": "energyOnlyBidPrice5",
        "energy_only_bid_price5": "energyOnlyBidPrice5",
        "energy only bid mw6": "energyOnlyBidMw6",
        "energy_only_bid_mw6": "energyOnlyBidMw6",
        "energy only bid price6": "energyOnlyBidPrice6",
        "energy_only_bid_price6": "energyOnlyBidPrice6",
        "energy only bid mw7": "energyOnlyBidMw7",
        "energy_only_bid_mw7": "energyOnlyBidMw7",
        "energy only bid price7": "energyOnlyBidPrice7",
        "energy_only_bid_price7": "energyOnlyBidPrice7",
        "energy only bid mw8": "energyOnlyBidMw8",
        "energy_only_bid_mw8": "energyOnlyBidMw8",
        "energy only bid price8": "energyOnlyBidPrice8",
        "energy_only_bid_price8": "energyOnlyBidPrice8",
        "energy only bid mw9": "energyOnlyBidMw9",
        "energy_only_bid_mw9": "energyOnlyBidMw9",
        "energy only bid price9": "energyOnlyBidPrice9",
        "energy_only_bid_price9": "energyOnlyBidPrice9",
        "energy only bid mw10": "energyOnlyBidMw10",
        "energy_only_bid_mw10": "energyOnlyBidMw10",
        "energy only bid price10": "energyOnlyBidPrice10",
        "energy_only_bid_price10": "energyOnlyBidPrice10",
        "energy only offer mw1": "energyOnlyBidMw1",
        "energy_only_offer_mw1": "energyOnlyBidMw1",
        "energy only offer price1": "energyOnlyBidPrice1",
        "energy_only_offer_price1": "energyOnlyBidPrice1",
        "energy only offer mw2": "energyOnlyBidMw2",
        "energy_only_offer_mw2": "energyOnlyBidMw2",
        "energy only offer price2": "energyOnlyBidPrice2",
        "energy_only_offer_price2": "energyOnlyBidPrice2",
        "energy only offer mw3": "energyOnlyBidMw3",
        "energy_only_offer_mw3": "energyOnlyBidMw3",
        "energy only offer price3": "energyOnlyBidPrice3",
        "energy_only_offer_price3": "energyOnlyBidPrice3",
        "energy only offer mw4": "energyOnlyBidMw4",
        "energy_only_offer_mw4": "energyOnlyBidMw4",
        "energy only offer price4": "energyOnlyBidPrice4",
        "energy_only_offer_price4": "energyOnlyBidPrice4",
        "energy only offer mw5": "energyOnlyBidMw5",
        "energy_only_offer_mw5": "energyOnlyBidMw5",
        "energy only offer price5": "energyOnlyBidPrice5",
        "energy_only_offer_price5": "energyOnlyBidPrice5",
        "energy only offer mw6": "energyOnlyBidMw6",
        "energy_only_offer_mw6": "energyOnlyBidMw6",
        "energy only offer price6": "energyOnlyBidPrice6",
        "energy_only_offer_price6": "energyOnlyBidPrice6",
        "energy only offer mw7": "energyOnlyBidMw7",
        "energy_only_offer_mw7": "energyOnlyBidMw7",
        "energy only offer price7": "energyOnlyBidPrice7",
        "energy_only_offer_price7": "energyOnlyBidPrice7",
        "energy only offer mw8": "energyOnlyBidMw8",
        "energy_only_offer_mw8": "energyOnlyBidMw8",
        "energy only offer price8": "energyOnlyBidPrice8",
        "energy_only_offer_price8": "energyOnlyBidPrice8",
        "energy only offer mw9": "energyOnlyBidMw9",
        "energy_only_offer_mw9": "energyOnlyBidMw9",
        "energy only offer price9": "energyOnlyBidPrice9",
        "energy_only_offer_price9": "energyOnlyBidPrice9",
        "energy only offer mw10": "energyOnlyBidMw10",
        "energy_only_offer_mw10": "energyOnlyBidMw10",
        "energy only offer price10": "energyOnlyBidPrice10",
        "energy_only_offer_price10": "energyOnlyBidPrice10",
        "energy only bid id": "bidId",
        "energy_only_bid_id": "bidId",
        "multi-hour block indicator": "multiHourBlock",
        "multi-hour_block_indicator": "multiHourBlock",
        "multi_hour_block_indicator": "multiHourBlock",
        "block/curve indicator": "blockCurve",
        "block_curve_indicator": "blockCurve",
        "block/curve_indicator": "blockCurve",
    },
    "offer_awards": {
        "delivery date": "deliveryDate",
        "delivery_date": "deliveryDate",
        "hour ending": "hourEnding",
        "hour_ending": "hourEnding",
        "settlement point": "settlementPointName",
        "settlement_point": "settlementPointName",
        "qse name": "qseName",
        "qse_name": "qseName",
        "energy only offer award in mw": "energyOnlyOfferAwardInMW",
        "energy_only_offer_award_in_mw": "energyOnlyOfferAwardInMW",
        "settlement point price": "settlementPointPrice",
        "settlement_point_price": "settlementPointPrice",
        "offer id": "offerId",
        "offer_id": "offerId",
    },
    "offers": {
        "delivery date": "deliveryDate",
        "delivery_date": "deliveryDate",
        "hour ending": "hourEnding",
        "hour_ending": "hourEnding",
        "settlement point": "settlementPointName",
        "settlement_point": "settlementPointName",
        "qse name": "qseName",
        "qse_name": "qseName",
        "energy only offer mw1": "energyOnlyOfferMW1",
        "energy_only_offer_mw1": "energyOnlyOfferMW1",
        "energy only offer price1": "energyOnlyOfferPrice1",
        "energy_only_offer_price1": "energyOnlyOfferPrice1",
        "energy only offer mw2": "energyOnlyOfferMW2",
        "energy_only_offer_mw2": "energyOnlyOfferMW2",
        "energy only offer price2": "energyOnlyOfferPrice2",
        "energy_only_offer_price2": "energyOnlyOfferPrice2",
        "energy only offer mw3": "energyOnlyOfferMW3",
        "energy_only_offer_mw3": "energyOnlyOfferMW3",
        "energy only offer price3": "energyOnlyOfferPrice3",
        "energy_only_offer_price3": "energyOnlyOfferPrice3",
        "energy only offer mw4": "energyOnlyOfferMW4",
        "energy_only_offer_mw4": "energyOnlyOfferMW4",
        "energy only offer price4": "energyOnlyOfferPrice4",
        "energy_only_offer_price4": "energyOnlyOfferPrice4",
        "energy only offer mw5": "energyOnlyOfferMW5",
        "energy_only_offer_mw5": "energyOnlyOfferMW5",
        "energy only offer price5": "energyOnlyOfferPrice5",
        "energy_only_offer_price5": "energyOnlyOfferPrice5",
        "energy only offer mw6": "energyOnlyOfferMW6",
        "energy_only_offer_mw6": "energyOnlyOfferMW6",
        "energy only offer price6": "energyOnlyOfferPrice6",
        "energy_only_offer_price6": "energyOnlyOfferPrice6",
        "energy only offer mw7": "energyOnlyOfferMW7",
        "energy_only_offer_mw7": "energyOnlyOfferMW7",
        "energy only offer price7": "energyOnlyOfferPrice7",
        "energy_only_offer_price7": "energyOnlyOfferPrice7",
        "energy only offer mw8": "energyOnlyOfferMW8",
        "energy_only_offer_mw8": "energyOnlyOfferMW8",
        "energy only offer price8": "energyOnlyOfferPrice8",
        "energy_only_offer_price8": "energyOnlyOfferPrice8",
        "energy only offer mw9": "energyOnlyOfferMW9",
        "energy_only_offer_mw9": "energyOnlyOfferMW9",
        "energy only offer price9": "energyOnlyOfferPrice9",
        "energy_only_offer_price9": "energyOnlyOfferPrice9",
        "energy only offer mw10": "energyOnlyOfferMW10",
        "energy_only_offer_mw10": "energyOnlyOfferMW10",
        "energy only offer price10": "energyOnlyOfferPrice10",
        "energy_only_offer_price10": "energyOnlyOfferPrice10",
        "energy only offer id": "offerId",
        "energy_only_offer_id": "offerId",
        "multi-hour_block_indicator": "multiHourBlock",
        "multi-hour block indicator": "multiHourBlock",
        "multi_hour_block_indicator": "multiHourBlock",
        "block/curve indicator": "blockCurve",
        "block_curve_indicator": "blockCurve",
        "block/curve_indicator": "blockCurve",
    },
}
