# New mappings for different CSV types
COLUMN_MAPPINGS = {
    "settlement_point_prices": {
        "deliverydate": "DeliveryDate",
        "delivery_date": "DeliveryDate",
        "deliveryDate": "DeliveryDate",
        "DeliveryDate": "DeliveryDate",
        "deliveryhour": "DeliveryHour",
        "delivery_hour": "DeliveryHour",
        "deliveryHour": "DeliveryHour",
        "DeliveryHour": "DeliveryHour",
        "deliveryinterval": "DeliveryInterval",
        "delivery_interval": "DeliveryInterval",
        "deliveryInterval": "DeliveryInterval",
        "DeliveryInterval": "DeliveryInterval",
        "settlementPoint": "SettlementPointName",
        "settlementpointname": "SettlementPointName",
        "settlement_point_name": "SettlementPointName",
        "settlementPointName": "SettlementPointName",
        "SettlementPointName": "SettlementPointName",
        "settlementpointtype": "SettlementPointType",
        "settlement_point_type": "SettlementPointType",
        "settlementPointType": "SettlementPointType",
        "SettlementPointType": "SettlementPointType",
        "settlementpointprice": "SettlementPointPrice",
        "settlement_point_price": "SettlementPointPrice",
        "settlementPointPrice": "SettlementPointPrice",
        "SettlementPointPrice": "SettlementPointPrice",
        "dstflag": "DSTFlag",
        "dst_flag": "DSTFlag",
        "DSTFlag": "DSTFlag",
        "dstFlag": "DSTFlag",
    },
    "bid_awards": {
        "delivery date": "DeliveryDate",
        "delivery_date": "DeliveryDate",
        "deliveryDate": "DeliveryDate",
        "DeliveryDate": "DeliveryDate",
        "hour ending": "HourEnding",
        "hour_ending": "HourEnding",
        "hourEnding": "HourEnding",
        "HourEnding": "HourEnding",
        "settlement point": "SettlementPoint",
        "settlement_point": "SettlementPoint",
        "settlementPointName": "SettlementPoint",
        "SettlementPointName": "SettlementPoint",
        "qse name": "QSEName",
        "qse_name": "QSEName",
        "qseName": "QSEName",
        "QSEName": "QSEName",
        "energy only bid award mw": "EnergyOnlyBidAwardMW",
        "energy_only_bid_award_mw": "EnergyOnlyBidAwardMW",
        "settlement point price": "SettlementPointPrice",
        "settlement_point_price": "SettlementPointPrice",
        "bid id": "BidId",
        "bid_id": "BidId",
        "bidId": "BidId",
        "BidId": "BidId",
    },
    "bids": {
        "delivery date": "DeliveryDate",
        "delivery_date": "DeliveryDate",
        "deliveryDate": "DeliveryDate",
        "DeliveryDate": "DeliveryDate",
        "hour ending": "HourEnding",
        "hour_ending": "HourEnding",
        "hourEnding": "HourEnding",
        "HourEnding": "HourEnding",
        "settlement point": "SettlementPoint",
        "settlement_point": "SettlementPoint",
        "settlementPointName": "SettlementPoint",
        "SettlementPointName": "SettlementPoint",
        "qse name": "QSEName",
        "qse_name": "QSEName",
        "qseName": "QSEName",
        "QSEName": "QSEName",
        "energy only bid mw1": "EnergyOnlyBidMW1",
        "energy only bid price1": "EnergyOnlyBidPrice1",
        "energy only bid mw2": "EnergyOnlyBidMW2",
        "energy only bid price2": "EnergyOnlyBidPrice2",
        "energy only bid mw3": "EnergyOnlyBidMW3",
        "energy only bid price3": "EnergyOnlyBidPrice3",
        "energy only bid mw4": "EnergyOnlyBidMW4",
        "energy only bid price4": "EnergyOnlyBidPrice4",
        "energy only bid mw5": "EnergyOnlyBidMW5",
        "energy only bid price5": "EnergyOnlyBidPrice5",
        "energy only bid mw6": "EnergyOnlyBidMW6",
        "energy only bid price6": "EnergyOnlyBidPrice6",
        "energy only bid mw7": "EnergyOnlyBidMW7",
        "energy only bid price7": "EnergyOnlyBidPrice7",
        "energy only bid mw8": "EnergyOnlyBidMW8",
        "energy only bid price8": "EnergyOnlyBidPrice8",
        "energy only bid mw9": "EnergyOnlyBidMW9",
        "energy only bid price9": "EnergyOnlyBidPrice9",
        "energy only bid mw10": "EnergyOnlyBidMW10",
        "energy only bid price10": "EnergyOnlyBidPrice10",
        "energy only bid id": "EnergyOnlyBidID",
        "energy_only_bid_id": "EnergyOnlyBidID",
        "multi-hour block indicator": "MultiHourBlockIndicator",
        "block/curve indicator": "BlockCurveIndicator",
    },
    "offer_awards": {
        "delivery date": "deliveryDate",
        "delivery_date": "deliveryDate",
        "hour ending": "hourEnding",
        "hour_ending": "hourEnding",
        "settlement point": "settlementPointName",
        "settlement_point": "settlementPointName",
        "qse name": "qseName",
        "qse_name": "qseName",
        "energy only offer award in mw": "energyOnlyOfferAwardInMW",
        "energy_only_offer_award_in_mw": "energyOnlyOfferAwardInMW",
        "settlement point price": "settlementPointPrice",
        "settlement_point_price": "settlementPointPrice",
        "offer id": "offerId",
        "offer_id": "offerId",
    },
    "offers": {
        "delivery date": "deliveryDate",
        "delivery_date": "deliveryDate",
        "hour ending": "hourEnding",
        "hour_ending": "hourEnding",
        "settlement point": "settlementPointName",
        "settlement_point": "settlementPointName",
        "qse name": "qseName",
        "qse_name": "qseName",
        "energy only offer mw1": "energyOnlyOfferMW1",
        "energy_only_offer_mw1": "energyOnlyOfferMW1",
        "energy only offer price1": "energyOnlyOfferPrice1",
        "energy_only_offer_price1": "energyOnlyOfferPrice1",
        "energy only offer mw2": "energyOnlyOfferMW2",
        "energy_only_offer_mw2": "energyOnlyOfferMW2",
        "energy only offer price2": "energyOnlyOfferPrice2",
        "energy_only_offer_price2": "energyOnlyOfferPrice2",
        "energy only offer mw3": "energyOnlyOfferMW3",
        "energy_only_offer_mw3": "energyOnlyOfferMW3",
        "energy only offer price3": "energyOnlyOfferPrice3",
        "energy_only_offer_price3": "energyOnlyOfferPrice3",
        "energy only offer mw4": "energyOnlyOfferMW4",
        "energy_only_offer_mw4": "energyOnlyOfferMW4",
        "energy only offer price4": "energyOnlyOfferPrice4",
        "energy_only_offer_price4": "energyOnlyOfferPrice4",
        "energy only offer mw5": "energyOnlyOfferMW5",
        "energy_only_offer_mw5": "energyOnlyOfferMW5",
        "energy only offer price5": "energyOnlyOfferPrice5",
        "energy_only_offer_price5": "energyOnlyOfferPrice5",
        "energy only offer mw6": "energyOnlyOfferMW6",
        "energy_only_offer_mw6": "energyOnlyOfferMW6",
        "energy only offer price6": "energyOnlyOfferPrice6",
        "energy_only_offer_price6": "energyOnlyOfferPrice6",
        "energy only offer mw7": "energyOnlyOfferMW7",
        "energy_only_offer_mw7": "energyOnlyOfferMW7",
        "energy only offer price7": "energyOnlyOfferPrice7",
        "energy_only_offer_price7": "energyOnlyOfferPrice7",
        "energy only offer mw8": "energyOnlyOfferMW8",
        "energy_only_offer_mw8": "energyOnlyOfferMW8",
        "energy only offer price8": "energyOnlyOfferPrice8",
        "energy_only_offer_price8": "energyOnlyOfferPrice8",
        "energy only offer mw9": "energyOnlyOfferMW9",
        "energy_only_offer_mw9": "energyOnlyOfferMW9",
        "energy only offer price9": "energyOnlyOfferPrice9",
        "energy_only_offer_price9": "energyOnlyOfferPrice9",
        "energy only offer mw10": "energyOnlyOfferMW10",
        "energy_only_offer_mw10": "energyOnlyOfferMW10",
        "energy only offer price10": "energyOnlyOfferPrice10",
        "energy_only_offer_price10": "energyOnlyOfferPrice10",
        "energy only offer id": "offerId",
        "energy_only_offer_id": "offerId",
        "multi-hour_block_indicator": "multiHourBlock",
        "multi-hour block indicator": "multiHourBlock",
        "multi_hour_block_indicator": "multiHourBlock",
        "block/curve indicator": "blockCurve",
        "block_curve_indicator": "blockCurve",
        "block/curve_indicator": "blockCurve",
    },
}
