name: CI

on:
  push:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      ERCOT_API_SUBSCRIPTION_KEY: ${{ secrets.ERCOT_API_SUBSCRIPTION_KEY }}
      ERCOT_API_BASE_URL_DAM: ${{ secrets.ERCOT_API_BASE_URL_DAM }}
      ERCOT_API_BASE_URL_SETTLEMENT: ${{ secrets.ERCOT_API_BASE_URL_SETTLEMENT }}
      ERCOT_API_USERNAME: ${{ secrets.ERCOT_API_USERNAME }}
      ERCOT_API_PASSWORD: ${{ secrets.ERCOT_API_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest pytest-cov coverage  # Install test dependencies explicitly
          pip install .[test]
        
      - name: Set environment variables
        run: |
          echo "ERCOT_API_SUBSCRIPTION_KEY=${{ secrets.ERCOT_API_SUBSCRIPTION_KEY }}" >> $GITHUB_ENV
          echo "ERCOT_API_BASE_URL_DAM=${{ secrets.ERCOT_API_BASE_URL_DAM }}" >> $GITHUB_ENV
          echo "ERCOT_API_BASE_URL_SETTLEMENT=${{ secrets.ERCOT_API_BASE_URL_SETTLEMENT }}" >> $GITHUB_ENV
          echo "ERCOT_API_USERNAME=${{ secrets.ERCOT_API_USERNAME }}" >> $GITHUB_ENV
          echo "ERCOT_API_PASSWORD=${{ secrets.ERCOT_API_PASSWORD }}" >> $GITHUB_ENV

      - name: Run tests with coverage
        run: |
          python -m pytest --cov=ercot_scraping --cov-report=xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false